framework:
    http_client:
        scoped_clients:
            binance.client:
                base_uri: '%env(BINANCE_API_BASE_URL)%'
                headers:
                    'Content-Type': 'application/json'
                    'Accept': 'application/json'
                timeout: 10
                max_redirects: 3
