# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    binance_base_uri: '%env(BINANCE_API_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    CryptoRate\:
        resource: '../src/'

    CryptoRate\DataLayer\Http\Binance\BinanceHttpClient:
        arguments:
            $binanceHttpClient: '@binance.client'
            $binanceBaseUri: '%binance_base_uri%'

    CryptoRate\DataLayer\Http\Binance\BinanceHttpClientInterface: '@CryptoRate\DataLayer\Http\Binance\BinanceHttpClient'
